appname="Hydrogen"
appver="origin"
appcode="15"
appsdk="21"
path_pattern=""
packagename="com.zhihu.hydrogen"
theme="Theme_Material"
app_key=""
app_channel=""
developer=""
description=""
debugmode=true
user_permission={
  "INTERNET",
  "READ_EXTERNAL_STORAGE",
  "REQUEST_INSTALL_PACKAGES",
  "WRITE_EXTERNAL_STORAGE"
}
